/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Output.Submenu;

import Output.Auth.FormLogin;
import Output.Submenu.Mahasiswa.CariPenyumbangBuku;
import View.BookNew;
import View.Peminjaman;

/**
 *
 * @author milea
 */
public class Dashboard extends javax.swing.JFrame {

    int userId;

    public Dashboard(int userId) {
        this.userId = userId;
        initComponents();
    }

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        this.dispose();
        new FormLogin().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        menuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuDashboard = new javax.swing.JMenu();
        menuBuku = new javax.swing.JMenu();
        menuSkripsi = new javax.swing.JMenu();
        menuPeminjaman = new javax.swing.JMenu();
        menuMahasiswa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SI Buku");
        setResizable(false);

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setPreferredSize(new java.awt.Dimension(1240, 680));
        panelMain.setLayout(new java.awt.BorderLayout());

        menuFile.setText("File");
        menuFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFileMouseClicked(evt);
            }
        });
        menuBar1.add(menuFile);

        menuDashboard.setText("Dashboard");
        menuBar1.add(menuDashboard);

        menuBuku.setText("Buku");
        menuBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBukuMouseClicked(evt);
            }
        });
        menuBar1.add(menuBuku);

        menuSkripsi.setText("Skripsi");
        menuBar1.add(menuSkripsi);

        menuPeminjaman.setText("Peminjaman");
        menuPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPeminjamanMouseClicked(evt);
            }
        });
        menuBar1.add(menuPeminjaman);

        menuMahasiswa.setText("Data Mahasiswa");
        menuMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMahasiswaMouseClicked(evt);
            }
        });
        menuBar1.add(menuMahasiswa);

        setJMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFileMouseClicked

    private void menuBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBukuMouseClicked
        // TODO add your handling code here:
        System.out.println(userId);
        panelMain.removeAll();
        panelMain.add(new BookNew(userId));
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_menuBukuMouseClicked

    private void menuPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPeminjamanMouseClicked
        // TODO add your handling code here:
        System.out.println(userId);
        panelMain.removeAll();
        panelMain.add(new Peminjaman(userId));
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_menuPeminjamanMouseClicked

    private void menuMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMahasiswaMouseClicked
        // TODO add your handling code here:
        new CariPenyumbangBuku(userId).setVisible(true);
    }//GEN-LAST:event_menuMahasiswaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar1;
    private javax.swing.JMenu menuBuku;
    private javax.swing.JMenu menuDashboard;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuMahasiswa;
    private javax.swing.JMenu menuPeminjaman;
    private javax.swing.JMenu menuSkripsi;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
